### PR TITLE
Series and expire

### PR DESCRIPTION
**Pull request by rgc99**
The series information is not working. The problem is because the regular expression is looking for 'Episode' and this appears to have changed to 'Ep' which in turn is causing the series to fail. Also handle where there is series but no episode information.

I would also like to get the expire date. This is being harvested from the xml and sent to Kodi as lastplayed. ListItem.setInfo does not really have a video value for an expiry date.

### CODE REVIEW

**Comment by andybotting** [comment]
Thanks!

**Comment by andybotting** [comment]
We need to handle both Ep and Episode it seems, and there was an issue with the date/time parsing, which I've also fixed.

I'm not sure I like the expire field in the lastplayed field. What about if we just added it to the end of the program description instead?

**Comment by rgc99** [comment]
Not crazy myself about the lastplayed field. Kodi doesn't seem to have a
dedicated value which is the proper solution. I guess add it to the end of
the program description.

 

 

  _____

**Comment by andybotting** [comment]
OK, I've removed it from lastplayed, and added it to the end of the description. Works pretty well I think.

I've just pushed v1.6.8 to the Catch Up TV AU repository, so should update automatically if you're using it.

cheers

**Pull request merged**
